### ISSUE TITLE
get null ptr if the node doesn't exist

### ISSUE THREAD

**Issue by johnzeng** [maciej/etcd-client#18]
I call the get method of the client, if the node exist, it works fine, but if the node doesn't exist, it return the following error:

```
[error]   ! return in success
[error]    null (EtcdMessage.scala:52)
[error] me.maciejb.etcd.client.EtcdError$.apply(EtcdMessage.scala:52)
[error] me.maciejb.etcd.client.impl.EtcdJsonProtocol$$anon$1.read(EtcdJsonProtocol.scala:30)
[error] me.maciejb.etcd.client.impl.EtcdJsonProtocol$$anon$1.read(EtcdJsonProtocol.scala:15)
[error] spray.json.JsValue.convertTo(JsValue.scala:31)
[error] me.maciejb.etcd.client.impl.EtcdClientImpl$$anonfun$3$$anonfun$apply$4.apply(EtcdClientImpl.scala:127)
[error] me.maciejb.etcd.client.impl.EtcdClientImpl$$anonfun$3$$anonfun$apply$4.apply(EtcdClientImpl.scala:124)
```

**Comment by maciej** [comment]
@Misfit-John thanks for reporting it. I'll have a loot at it.

**Comment by maciej** [comment]
@Misfit-John could you include the code causing the exception?

**Comment by johnzeng** [comment]
I use play framework to do this. my etcd is running on dockerhost:4001, if I create a "hello1" node on it, it won't throw any error, but if I don't create it, if will throw the nullptr exception.

``` scala
class Application extends Controller {
  implicit val actor:ActorSystem = ActorSystem()
  implicit val mat = ActorMaterializer()
//  implicit val ec = system.dispatcher

  val client = EtcdClient("dockerhost", 4001)

  def ping = Action.async{
    client.get("hello1").map{ response =>
      println(response)
      Ok(response.toString)
    }
  }

}
```

**Comment by maciej** [comment]
@Misfit-John which etcd version are you using?

**Comment by johnzeng** [comment]
I pulled the docker version etcd from dockerhub, https://hub.docker.com/r/microbox/etcd/, as it said, I think the version should be 2.1.1 , hmm, quite an old one.

**Comment by maciej** [comment]
@Misfit-John could you, please try the following code instead of `client.get("hello1")`:

``` scala
etcd.get("foo-bar").map(Some(_)).recover {
  case _: EtcdCommandError => None
}
```

That should wrap an existing key to `Some(value)` and a get on a nonexistent key should result in a `None` returned.

Does it work for you?

**Comment by johnzeng** [comment]
Hmm, do fix my problem,thanks. but I still think it will be better if you fix the null problem or just update the readmeio to let others know what's going on with this issue.
