### ISSUE TITLE
Allow client construction with optional HTTP auth credentials

### ISSUE THREAD

**Issue by fat0wl** [maciej/etcd-client#20]
I'm using a 3rd party etcd provider and their instances require http auth. Unless I'm missing something in ClientConnectionSettings, I don't believe this is currently possible with your client library (though I really like it otherwise so don't want to switch to another). I was thinking of overriding call in EtcdClientImpl but it seems a bit too abstracted to be simply extended since this is a private method & the class is this impl class is instantiated explicitly in the client factory method. For now I will probably fork & try to add this feature unobtrusively, will be happy to submit a PR.

**Comment by fat0wl** [comment]
This is addressed in PR #21, though I'm wondering if instead of providing explicit support for these features it would be better just to allow for some HTTP-related factory methods to be passed in to customize construction of base HTTP objects?

**Comment by maciej** [comment]
@fat0wl as you can probably tell from my delayed reply to your issue report I'm not investing much effort and time to improve the library.

Feel free to take over or fork the project.

I'll release a new version with the PRs you've submitted soon.

**Comment by maciej** [comment]
Closing due to archival of the project.
