### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by fabianmurariu** [maciej/etcd-client#25]
In [EtcdClientImpl#33](https://github.com/maciej/etcd-client/blob/master/src/main/scala/me/maciejb/etcd/client/impl/EtcdClientImpl.scala#L33)

Is there any reason why you don't use a connection pool?

**Comment by maciej** [comment]
@fabianmurariu I no longer maintain the project. It's been too long that I last touched it, so I don't have an answer for your question off-hand. Feel free to fork it.
